// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/alex/pallavi-onsite/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/alex/pallavi-onsite/web/src/pages/NotFoundPage/NotFoundPage'
import MessageEditMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/EditMessagePage/EditMessagePage'
import MessageMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/MessagePage/MessagePage'
import MessageMessagesPageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/MessagesPage/MessagesPage'
import MessageNewMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/NewMessagePage/NewMessagePage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const MessageEditMessagePage: typeof MessageEditMessagePageType
  const MessageMessagePage: typeof MessageMessagePageType
  const MessageMessagesPage: typeof MessageMessagesPageType
  const MessageNewMessagePage: typeof MessageNewMessagePageType
}
