// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/alex/pallavi-onsite/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/alex/pallavi-onsite/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/alex/pallavi-onsite/web/src/pages/NotFoundPage/NotFoundPage'
import CitationCitationPageType from '/Users/alex/pallavi-onsite/web/src/pages/Citation/CitationPage/CitationPage'
import CitationCitationsPageType from '/Users/alex/pallavi-onsite/web/src/pages/Citation/CitationsPage/CitationsPage'
import CitationEditCitationPageType from '/Users/alex/pallavi-onsite/web/src/pages/Citation/EditCitationPage/EditCitationPage'
import CitationNewCitationPageType from '/Users/alex/pallavi-onsite/web/src/pages/Citation/NewCitationPage/NewCitationPage'
import CourtCourtPageType from '/Users/alex/pallavi-onsite/web/src/pages/Court/CourtPage/CourtPage'
import CourtCourtsPageType from '/Users/alex/pallavi-onsite/web/src/pages/Court/CourtsPage/CourtsPage'
import CourtEditCourtPageType from '/Users/alex/pallavi-onsite/web/src/pages/Court/EditCourtPage/EditCourtPage'
import CourtNewCourtPageType from '/Users/alex/pallavi-onsite/web/src/pages/Court/NewCourtPage/NewCourtPage'
import MessageEditMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/EditMessagePage/EditMessagePage'
import MessageMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/MessagePage/MessagePage'
import MessageMessagesPageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/MessagesPage/MessagesPage'
import MessageNewMessagePageType from '/Users/alex/pallavi-onsite/web/src/pages/Message/NewMessagePage/NewMessagePage'
import UserEditUserPageType from '/Users/alex/pallavi-onsite/web/src/pages/User/EditUserPage/EditUserPage'
import UserNewUserPageType from '/Users/alex/pallavi-onsite/web/src/pages/User/NewUserPage/NewUserPage'
import UserUserPageType from '/Users/alex/pallavi-onsite/web/src/pages/User/UserPage/UserPage'
import UserUsersPageType from '/Users/alex/pallavi-onsite/web/src/pages/User/UsersPage/UsersPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const CitationCitationPage: typeof CitationCitationPageType
  const CitationCitationsPage: typeof CitationCitationsPageType
  const CitationEditCitationPage: typeof CitationEditCitationPageType
  const CitationNewCitationPage: typeof CitationNewCitationPageType
  const CourtCourtPage: typeof CourtCourtPageType
  const CourtCourtsPage: typeof CourtCourtsPageType
  const CourtEditCourtPage: typeof CourtEditCourtPageType
  const CourtNewCourtPage: typeof CourtNewCourtPageType
  const MessageEditMessagePage: typeof MessageEditMessagePageType
  const MessageMessagePage: typeof MessageMessagePageType
  const MessageMessagesPage: typeof MessageMessagesPageType
  const MessageNewMessagePage: typeof MessageNewMessagePageType
  const UserEditUserPage: typeof UserEditUserPageType
  const UserNewUserPage: typeof UserNewUserPageType
  const UserUserPage: typeof UserUserPageType
  const UserUsersPage: typeof UserUsersPageType
}
