// This file was generated by RedwoodJS
import * as Cell from './CourtCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindCourtById, FindCourtByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CourtCell'

type CellInputs = CellProps<SuccessType, FindCourtById, typeof Cell, FindCourtByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
