// This file was generated by RedwoodJS
import * as Cell from './CitizenCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindCitizenById, FindCitizenByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CitizenCell'

type CellInputs = CellProps<SuccessType, FindCitizenById, typeof Cell, FindCitizenByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
