// This file was generated by RedwoodJS
import * as Cell from './MessageCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindMessageById, FindMessageByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './MessageCell'

type CellInputs = CellProps<SuccessType, FindMessageById, typeof Cell, FindMessageByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
