// This file was generated by RedwoodJS
import * as Cell from './CitizensCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindCitizens, FindCitizensVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CitizensCell'

type CellInputs = CellProps<SuccessType, FindCitizens, typeof Cell, FindCitizensVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
