// This file was generated by RedwoodJS
import * as Cell from './EditCitizenCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditCitizenById, EditCitizenByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditCitizenCell'

type CellInputs = CellProps<SuccessType, EditCitizenById, typeof Cell, EditCitizenByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
