// This file was generated by RedwoodJS
import * as Cell from './CitationCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindCitationById, FindCitationByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CitationCell'

type CellInputs = CellProps<SuccessType, FindCitationById, typeof Cell, FindCitationByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
