// This file was generated by RedwoodJS
import * as Cell from './CitationsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindCitations, FindCitationsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CitationsCell'

type CellInputs = CellProps<SuccessType, FindCitations, typeof Cell, FindCitationsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
